In [1]:
import pandas as pd

factories = pd.read_csv("../Datasets/tbl_factory.csv", index_col=0)
factories

        FCName  FCDemand FCRegion
FCID
FC00001   東京工場        28       関東
FC00002  木更津工場        29       関東
FC00003   多摩工場        31       関東
FC00004  横須賀工場        25       関東
FC00005   仙台工場        21       東北
FC00006   山形工場        30       東北
FC00007   那須工場        25       東北
FC00008   青森工場        16       東北

In [3]:
warehouse = pd.read_csv("../Datasets/tbl_warehouse.csv", index_col=0)
warehouse

        WHName  WHSupply WHRegion
WHID
WH00001   杉並倉庫        35       関東
WH00002   品川倉庫        41       関東
WH00003   豊洲倉庫        42       関東
WH00004   郡山倉庫        60       東北
WH00005   仙台倉庫        72       東北
WH00006   山形倉庫        65       東北

In [5]:
cost = pd.read_csv("../Datasets/rel_cost.csv", index_col=0)
cost.head()

            FCID     WHID  Cost
RCostID
1        FC00001  WH00001   0.4
2        FC00001  WH00002   0.8
3        FC00001  WH00003   1.5
4        FC00002  WH00001   0.9
5        FC00002  WH00002   0.8

In [6]:
trans = pd.read_csv("../Datasets/tbl_transaction.csv", index_col=0)
trans.head()

          TransactionDate     ToFC   FromWH  Quantity
TRID
0     2019-01-01 02:11:10  FC00004  WH00003        33
1     2019-01-01 06:12:42  FC00007  WH00006        19
2     2019-01-01 06:32:32  FC00006  WH00004        31
3     2019-01-01 07:17:06  FC00002  WH00003        18
4     2019-01-01 07:52:18  FC00001  WH00002        30

In [7]:
join_data = pd.merge(trans, cost, left_on=["ToFC", "FromWH"], right_on=["FCID", "WHID"], how="left")
join_data.head()

       TransactionDate     ToFC   FromWH  Quantity     FCID     WHID  Cost
0  2019-01-01 02:11:10  FC00004  WH00003        33  FC00004  WH00003   1.1
1  2019-01-01 06:12:42  FC00007  WH00006        19  FC00007  WH00006   1.3
2  2019-01-01 06:32:32  FC00006  WH00004        31  FC00006  WH00004   0.9
3  2019-01-01 07:17:06  FC00002  WH00003        18  FC00002  WH00003   1.6
4  2019-01-01 07:52:18  FC00001  WH00002        30  FC00001  WH00002   0.8

In [8]:
join_data = pd.merge(join_data, factories, left_on="ToFC", right_on="FCID", how="left")
join_data.head()

,TransactionDate,ToFC,FromWH,Quantity,FCID,WHID,Cost,FCName,FCDemand,FCRegion
0,2019-01-01 02:11:10,FC00004,WH00003,33,FC00004,WH00003,1.1,横須賀工場,25,関東
1,2019-01-01 06:12:42,FC00007,WH00006,19,FC00007,WH00006,1.3,那須工場,25,東北
2,2019-01-01 06:32:32,FC00006,WH00004,31,FC00006,WH00004,0.9,山形工場,30,東北
3,2019-01-01 07:17:06,FC00002,WH00003,18,FC00002,WH00003,1.6,木更津工場,29,関東
4,2019-01-01 07:52:18,FC00001,WH00002,30,FC00001,WH00002,0.8,東京工場,28,関東