In [70]:
import pandas as pd
import numpy as np

In [71]:
train = pd.read_csv("../Datasets/train.csv")
train.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [72]:
test = pd.read_csv("../Datasets/test.csv")
test.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [73]:
Main = train[["Survived", "Pclass", "Name", "Sex", "Age"]]
Main

,Survived,Pclass,Name,Sex,Age
0,0,3,"Braund, Mr. Owen Harris",male,22.0
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0
2,1,3,"Heikkinen, Miss. Laina",female,26.0
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0
4,0,3,"Allen, Mr. William Henry",male,35.0
...,...,...,...,...,...
886,0,2,"Montvila, Rev. Juozas",male,27.0
887,1,1,"Graham, Miss. Margaret Edith",female,19.0
888,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN
889,1,1,"Behr, Mr. Karl Howell",male,26.0
890,0,3,"Dooley, Mr. Patrick",male,32.0

In [74]:
Men = Main.loc[Main.Sex=="male"]["Survived"]
Men

0      0
4      0
5      0
6      0
7      0
      ..
883    0
884    0
886    0
889    1
890    0
Name: Survived, Length: 577, dtype: int64

In [75]:
Men.value_counts()

Survived
0    468
1    109
Name: count, dtype: int64

In [76]:
Rate_Men = sum(Men) / len(Men)
Rate_Men

0.18890814558058924

In [77]:
Women = Main.loc[Main.Sex=="female"]["Survived"]
Women

1      1
2      1
3      1
8      1
9      1
      ..
880    1
882    0
885    0
887    1
888    0
Name: Survived, Length: 314, dtype: int64

In [78]:
Women.value_counts()

Survived
1    233
0     81
Name: count, dtype: int64

In [79]:
Rate_Women = sum(Women) / len(Women)
Rate_Women

0.7420382165605095

In [80]:
Rate_Pclass =Main.groupby("Pclass").sum()["Survived"]
Rate_Pclass

Pclass
1    136
2     87
3    119
Name: Survived, dtype: int64

In [81]:
Rate_Pclass =Main.groupby(["Pclass","Sex"]).sum()["Survived"]
Rate_Pclass

Pclass  Sex
1       female    91
        male      45
2       female    70
        male      17
3       female    72
        male      47
Name: Survived, dtype: int64

どの席のどの性別の生存

In [82]:
Sex_dummies = pd.get_dummies(Main, columns=["Sex"])
Sex_dummies

,Survived,Pclass,Name,Age,Sex_female,Sex_male
0,0,3,"Braund, Mr. Owen Harris",22.0,False,True
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",38.0,True,False
2,1,3,"Heikkinen, Miss. Laina",26.0,True,False
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",35.0,True,False
4,0,3,"Allen, Mr. William Henry",35.0,False,True
...,...,...,...,...,...,...
886,0,2,"Montvila, Rev. Juozas",27.0,False,True
887,1,1,"Graham, Miss. Margaret Edith",19.0,True,False
888,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",NaN,True,False
889,1,1,"Behr, Mr. Karl Howell",26.0,False,True
890,0,3,"Dooley, Mr. Patrick",32.0,False,True

In [84]:
Sex_dummies.astype({"Sex_female": int, "Sex_male": int})

,Survived,Pclass,Name,Age,Sex_female,Sex_male
0,0,3,"Braund, Mr. Owen Harris",22.0,0,1
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",38.0,1,0
2,1,3,"Heikkinen, Miss. Laina",26.0,1,0
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",35.0,1,0
4,0,3,"Allen, Mr. William Henry",35.0,0,1
...,...,...,...,...,...,...
886,0,2,"Montvila, Rev. Juozas",27.0,0,1
887,1,1,"Graham, Miss. Margaret Edith",19.0,1,0
888,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",NaN,1,0
889,1,1,"Behr, Mr. Karl Howell",26.0,0,1
890,0,3,"Dooley, Mr. Patrick",32.0,0,1

In [85]:
Sex_dummies

,Survived,Pclass,Name,Age,Sex_female,Sex_male
0,0,3,"Braund, Mr. Owen Harris",22.0,False,True
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",38.0,True,False
2,1,3,"Heikkinen, Miss. Laina",26.0,True,False
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",35.0,True,False
4,0,3,"Allen, Mr. William Henry",35.0,False,True
...,...,...,...,...,...,...
886,0,2,"Montvila, Rev. Juozas",27.0,False,True
887,1,1,"Graham, Miss. Margaret Edith",19.0,True,False
888,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",NaN,True,False
889,1,1,"Behr, Mr. Karl Howell",26.0,False,True
890,0,3,"Dooley, Mr. Patrick",32.0,False,True

In [86]:
Sex_dummies = Sex_dummies.astype({"Sex_female": int, "Sex_male": int})
Sex_dummies

,Survived,Pclass,Name,Age,Sex_female,Sex_male
0,0,3,"Braund, Mr. Owen Harris",22.0,0,1
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",38.0,1,0
2,1,3,"Heikkinen, Miss. Laina",26.0,1,0
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",35.0,1,0
4,0,3,"Allen, Mr. William Henry",35.0,0,1
...,...,...,...,...,...,...
886,0,2,"Montvila, Rev. Juozas",27.0,0,1
887,1,1,"Graham, Miss. Margaret Edith",19.0,1,0
888,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",NaN,1,0
889,1,1,"Behr, Mr. Karl Howell",26.0,0,1
890,0,3,"Dooley, Mr. Patrick",32.0,0,1